### ISSUE TITLE
Winnie OKR

### ISSUE THREAD

**Issue by jazcheng** [bitprj/people#107]
**Objective: Ensure 1:1 and team meetings happen**
- [x] create an airtable form that asks for 
- name
- position
- 2 questions: "have you had all your 1:1 meetings yet" and "have you had your team meeting yet" and have a checkbox along with each question with answer choice "I have"

**later tasks**
- [x] send out this form to every manager & director every monday and check form on every friday
- [x] send names to @jazcheng of those that don't fill out the form by friday

let me know if you have questions! pls come back soooon :)

**Deadline to create form: Friday, 5/22**

**Comment by beccatran** [comment]
all meetings were recorded on the airtable form!
