### ISSUE TITLE
Collin OKR

### ISSUE THREAD

**Issue by jazcheng** [bitprj/people#109]
**Objectives: Educate others on github**

- [ ] two options: take minh-tu's github webinar break it into smaller videos or make your own videos (make each video about a different topic)
- [ ] post these short videos on guru
- [ ] post guru card and make an announcement in the #general channel on slack about these videos

welcome to l&d collin!!

**Deadline: Wednesday, 5/27**

**Comment by beccatran** [comment]
again this will be a onboarding OKR
