### ISSUE TITLE
Document How Issues Should Be Completed

### ISSUE THREAD

**Issue by kavuong** [bitprj/people#13]
*Objectives*
To document a protocol of handling issues.
- [x] Receiving Issues (Slack reminder, assignee)
- [x] Explaining Objectives/Collaborators/Deadline structure
- [x] Explain checking off issues as tasks are completed
- [x] Including Issues in Pull Requests

*Collaborators and Tasks*
@minhtumn 

*Deadline*
Wed, 4/1

**Comment by kavuong** [comment]
> not to intimidate you, but this is what I would do: (and what I currently do with DevRel)
1. Plan out specific deliverables that have to be done
2. Place those deliverables in meeting notes (you can use the Development-Docs-Sync meeting notes i made above as reference)
3. Have an idea of who should be assigned what *before the meeting*
4. At the end of the meeting, you should outline the deliverables very clearly, and get them *to agree to the provided deadlines*
5. Set-up issue with checklist and agreed-to deadlines (just like #30 Bible for Devs issue above)
6. Emphasize that you are very excited and open to answer any questions at any time.
7. Set up a channel for every major onboarding issue, and *encourage them to ask questions in that group,* that way they have a place to message you and the group
8. Follow-up a day before reminding them of the deadline and ask if there are any questions. Also ensure that they will finish by the agreed-to deadlines.
9. Day of, follow-up with them if they haven't checked off the github checkmarks, and make sure their work is in the proper format, if not, please follow-up 
<sub>[View in Slack](https://bitdarlene.slack.com/archives/DQCCA7R0C/p1585771133010300)</sub>

**Comment by lazyplatypus** [comment]
This documentation should be under "communication", not devrel
