### ISSUE TITLE
Amy OKRs

### ISSUE THREAD

**Issue by kphillips20** [bitprj/people#140]
** Objective: Continue important day-to-day tasks to ensure members a smooth transition into Bit Project. 
- [x] Onboard Marketing Applicants
- [x] Conduct Interviews

** Objective: Improve EduFlows. 
- [x] Make general Eduflow. 
- [x] Contact each director to add in information regarding their team/positions (see Slack message from Katie with more details about this). 

** Objective: Make application process more clear to new members. 
- [x] Create the introductory video that Daniel was talking about. 
- [x] Clarify the application process and enforce values. 

** Objective: Use personal connections to source more people for People Team!
- [x] Source at Purdue!

**Comment by amymaclaren** [comment]
Daniel also instructed me to source at Purdue for people for people

**Comment by kphillips20** [comment]
okay, great! I added it to your OKRs! :)
