### ISSUE TITLE
People Experience Evaluation Task

### ISSUE THREAD

**Issue by shreythecray** [bitprj/people#150]
# Due: Saturday June 13th
Evaluate current feedback collection methods including:
- 1:1 Meetings with Managers
- Team/Department Feedback
- Reporting Systems

## To do:

- [x] Create markdown report (on Notion)
- Outline proposal for improvement current measures and if applicable, create proposals for new feedback collection measures
- [x] Submit report on **Saturday June 13th** for review
- [x] Check review and make edits
- [x] Present report on **Sunday June 14th**

**Comment by beccatran** [comment]
went over the feedback process during the directors meeting, approved by everyone in the meeting.
