### ISSUE TITLE
Community Involvement

### ISSUE THREAD

**Issue by shreythecray** [bitprj/people#152]
# Due: Wednesday June 17th

> DRI: @amymaclaren 

- [x] Create a list of 5 social ideas for EACH tier. Place them in the  **Resources > Ideas for Socials. After you come up with each idea, ask for feedback in the #people-dept Slack channel.** 
    - 4 tiers for socials needed
        1. Bonding socials 
        2. Team socials (once a month)
        3. Department socials (once a month)
        4. Organization socials (once a month)
- [x] Create a list of feedback questions to ask to 1) newly onboarded members 2) existing members
    - Set up meetings with 5 members from each department to gather feedback
    - Create a master list of all the teams across Bit Project and create a schedule on when to join their meetings to gather monthly feedback
- [x] Host 1 weekly social event with at least 20 attendees
- [x]  Conduct 1-1s with all directors and develop report with pain points and valuable insights to improve our organization

**Comment by amymaclaren** [comment]
Hey! Since I have exam this weekend, I won’t be doing OKR’s. I will be still doing Onboarding. I’m still staying on top of the the Eduflow and reminding people. I think the managing consultants and people experience associates would do a great job at collecting feedback.
