### ISSUE TITLE
How To: Make Issues

### ISSUE THREAD

**Issue by shreythecray** [bitprj/people#24]
- [x] Document "How To: Make Issues" in GitBooks as a page under [GitHub Basics](https://about.bitproject.org/organization/github)
- [x] Add link to "How To: Make Issues" page under GitHub Issues section in GitHub Basics in GitBooks

Can use content from: https://help.github.com/en/github/managing-your-work-on-github/creating-an-issue

Just cite it at the bottom of the page if you use it

**Comment by minhtumn** [comment]
https://app.gitbook.com/@bit-project/s/bit-project/organization/github/how-to-make-issues
