### ISSUE TITLE
Add New Open Position: Social Media Specialist

### ISSUE THREAD

**Issue by shreythecray** [bitprj/people#30]
# Social Media Specialist

## Skills/Qualifications:
- Demonstrated background and experience in design
- Strong organization and written and verbal communication skills
- Ability to work on multiple projects at once
- Good teamwork skills
- Experience in sales and/or marketing

## Responsibilities:
- Creates social media campaigns from content ideation to implementation schedules
- Ensures brand recognition and consistency in marketing and social media messages by working with various departments, including Marketing, People, Developer Relations, and Engineering
- Prepares reports and leads discussions on analyses of interactions and visits for Marketing Team meetings and determines and executes action plan to improve social media marketing
- Distributes multimedia content to various social media avenues and increases organization's online presence into new social media platforms including Reddit, Facebook, LinkedIn, Twitter, and Instagram

## Goals
The Social Media Specialist is a crucial central member of the organization involved in creating ideas, publicity schedules, and implementation of plans to increase the online brand and presence of Bit Project. They work extensively with multiple teams to share content on all social media platforms and explore new strategies to improve analytics and attain quantitative benchmarks.

**Comment by beccatran** [comment]
https://www.bitproject.org/join
