### ISSUE TITLE
Underperforming

### ISSUE THREAD

**Issue by beccatran** [bitprj/people#32]
So far my two only solutions to underperforming is coaching and PDP which is placed under the management training. 

- [x] Outline on the process of what happens if someone underperforms
1. director has a talk with the person
2. director identifies areas that they are lacking and reports to me 
3. i file a report on airtable
4. i create a personalized training plan for the person
    1. completing tasks by a certain date 
    2. create assessments 
    3. i meet with the person to communicate their tasks
5. i track their progress and have 1:1s with them
6. track performance by grading assessments/other ways

- [x] Who talks to the underperformer/ who monitors their progression
- director talks first, then communicates their problems over to me
- i then deal with it

- [x] Where will this report get filed
- create private airtable base

- [x] Solutions/ Paths people can talk if they underperform

**Comment by jazcheng** [comment]
**Next Steps**
- [x]  document underperforming guidelines
- [x] wait until Winnie gathers feedback from directors/managers, then implement ways to address those problems
