### ISSUE TITLE
Figure out the general timeline and finalize it

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/people#4]
**Questions that NEED to be addressed**
- [ ] Who is doing what in this onboarding process
- [ ] How long will this take?
- [ ] Where will be documented? 
- [ ] What is the difference with Dev onboarding?

**Example Workflow**
- Application is processed
- Send automated email about “welcome to bit and please reserve a time on Daniel’s Calendly” 
- Daniel’s introduction to sets expectations, introduces the objective, invites people to slack, and talk about being remote, Daniel refers them to their respective mentor/ director
- Newbies have 1:1 with directors. Directors refer to the task and they have 7 days to finish the onboarding. Directors are responsible to add them on all the platforms that we are using
- Newbies have to set another meeting with their respected director to talk about the tasks and directors need to ask for their feedbacks

**Comment by shreythecray** [comment]
How long will this take

**Comment by lazyplatypus** [comment]
I think that we should also think about webinars and other things like that
