### ISSUE TITLE
Spring Quarter 2nd round Feedback

### ISSUE THREAD

**Issue by winniezhang-23** [bitprj/people#41]
## Attend each meeting and collect feedback:
**Collect detailed notes in all meetings in GitHub**
**Ensure that all members of the team are in the feedback meeting (check with manager beforehand)**
- President:
- [ ] Daniel Kim

- Departments: (Directors)
- [x] DevRel (Kevin Vuong)
- [ ] Marketing (Shreya)
- [x] Engineering (Bryan W)
- [ ] People (Becca)

- Teams: (Managers)
- [x] Design (Rochelle Dai)
- [x] Writing (Victoria Xu)
- [x] IMC: Twitter (Steven Nian)
- [x] PrimaryEd (Jing)
- [ ] Recruitment (Owen)

Discuss the following:
- General feedback
- Communication w/ team, team manager, director
- Onboarding/experience of any new members
- Frustrations/concerns
- Things that have been going really well
- Things that are getting better but not there yet/need more work

## After Meetings:
- [ ] Categorize notes and **lead discussion** in weekly People Team meeting
- [ ] Determine **action plan** to solve issues
- [ ] Determine relevant deliverables and **create issues** for all

**Comment by beccatran** [comment]
@winniezhang-23 need updates
