### ISSUE TITLE
Finish up the Communication Webinar

### ISSUE THREAD

**Issue by beccatran** [bitprj/people#5]
- [x] find the software
- [x] film the Communication slides

**Comment by lazyplatypus** [comment]
Updates on this

**Comment by beccatran** [comment]
I am having a hard time using OBS could you help me out if you have time. I can't seem to fit the whole screen on my desktop

**Comment by shreythecray** [comment]
@beccatran can you expand on the example in slide 37 https://about.bitproject.org/organization/communication

**Comment by beccatran** [comment]
I showed the entire meeting template in the webinar itself
