### ISSUE TITLE
General GitHub Webinar

### ISSUE THREAD

**Issue by beccatran** [bitprj/people#6]
- [x] Create outline on google slides
- [x] Get feedback and approval 
- [x] Tell Rochelle to help edit the slides
- [x] Tell Vicky to help edit the slides 

- [x] Document what you put in the google slides to our Handbook

**Comment by lazyplatypus** [comment]
Discussed in Today's Meeting: Let's make the deadline for this Friday.

**Comment by minhtumn** [comment]
https://docs.google.com/presentation/d/1RqJbhBbA6pfget6H4kwTQNuL_dSlvpDFc5lXf1ylrQ8/edit?usp=sharing
