### ISSUE TITLE
Diversity and Inclusion Webinar

### ISSUE THREAD

**Issue by shreythecray** [bitprj/people#7]
- [x] More research
- W/ Vicky: Bias, fundamental attributions of error, and confidentiality 
- Reach out to Psych department
- [x] Working with Becca to create slides
- [x] Set up meeting with People Team to review slides
- [x] Review and edit webinar
- [x] Final feedback
- [x] Finalize webinar
- [x] Record webinar

**Comment by shreyagupta98** [comment]
You need to do this

**Comment by lazyplatypus** [comment]
Any Updates?

**Comment by shreythecray** [comment]
@lilyhem can we set up a meeting for Thursday to review the slides with the People team?

**Comment by lilyhem** [comment]
- [ ] add more information under "bias" 3/31/2020 

- [ ] finish slides 3/

**Comment by lilyhem** [comment]
> @lilyhem can we set up a meeting for Thursday to review the slides with the People team?

yes

**Comment by lilyhem** [comment]
- [x] Add more information under "bias" 3/31/2020 

-  Vicky

- [x] Finish Webinar slides by 4/1/2020 

- [x] People meeting to review slides 4/2/2020

- [x] Improve slides 4/2/2020

**Comment by lilyhem** [comment]
Diversity and Inclusion slides draft: https://docs.google.com/presentation/d/1oN1C4iuAAc2C0c1Wd59TWwYgpp9lSmcIrwmfLG5BcT4/edit?usp=sharing
