### ISSUE TITLE
Minh Tu: Onboarding Training

### ISSUE THREAD

**Issue by beccatran** [bitprj/people#82]
**Objectives: Update the onboarding training guide**

**Collaborators and Tasks**

- [x] Make sure that everything is up to date in the training 
- [x] During the applicant process, the onboarder is directly responsible for adding the applicant to ALL the workspaces, it is no longer the recruiter's job
- [x] Explain in details what each status means 

**Deadline: May 20th**

**Comment by minhtumn** [comment]
does this mean that onboarders are in charge of assigning the issue?

**Comment by beccatran** [comment]
yes the onboarders are in charge of assigning issues on github and inviting them to eduflow
