### ISSUE TITLE
Winnie OKR

### ISSUE THREAD

**Issue by jazcheng** [bitprj/people#85]
**Objective: Work on the FAQ page on the Handbook**
- [x] go through all the feedback we've gotten and identify common problems
- [x] identify solutions to those common problems
- [ ] document this in the handbook

**Comment by beccatran** [comment]
@winniezhang-23 updates??

**Comment by beccatran** [comment]
Discussed with Winnie earlier this week, all feedback from across all teams say that GitHub is their biggest issue. Relay that issue to the recruiting team.
