### ISSUE TITLE
Figure out Process for Internal Feedback

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/people#9]

**Comment by lazyplatypus** [comment]
> i think so far we only figured that a person would focus on one team. And talk individually to the reviewer and the dev. and join their team meeting to see what issues they may have.
<sub>[View in Slack](https://bitdarlene.slack.com/archives/C0100N2AMN1/p1585354934005000)</sub>

**Comment by beccatran** [comment]
https://docs.google.com/presentation/d/1AWHFHz8g-kGamffXDTxRQTOLdtv_6BVCy-ijdrf3wZQ/edit?usp=sharing
