### ISSUE TITLE
Townhall

### ISSUE THREAD

**Issue by beccatran** [bitprj/people#96]
This is a checklist for every Town Hall so we can prepare for it in a timely manner, please check this list as you complete it. The L&D manager is responsible for making the townhall happen

### DRI:

@jazcheng 

### Date of Town hall: 

[date]

### Checklist: 

- [x] Hold a meeting with L&D manager with director
- [x] Send out zoom link and information about townhall to the #general channel 
- [x] Create the event on google calendar 

- [x] Create slide deck
  - **President (club) Updates**
    - [x] Elections
  - **People team updates**
    - [ ] How-To mini live webinar (how to guru, etc)
  - **Engineering updates**
  - **Marketing updates**
  - **DevRel updates**
    - [x] Starting IMCs (everyone should be in corresponding #channels on Slack)
    - [ ] Introducing HS program (devrel as mentors)
  - [x] Retroly linked within townhall for discussion
- [x] Retroly sent out 3 days before town hall in #general channel 
- [x] Dry Run 1 day before the actual town hall

**Comment by lazyplatypus** [comment]
Adding Notes: 
President Updates
- [x] Explain National Org/ School Chapters
- [x] Mention the 4-5 School Chapters
- UC Davis
- USC
- NYU
- U of Illinois
- [x] Davis Chapter. Applications open now for three roles! 
- Elections Happening After Finals. 
- Everyone Is Able to Apply Regardless of Position. 
- Only Requirement: Been Active Member for 2 Months. 
- Ask Questions + Fill Out Airtable Form. 
- 2 week application period. Upload Loom about yourself (1-2 min), experience, why you want the position. (Guidelines of what's okay/not okay) 
- During Finals week, we will be assigning interview dates, 1st week of summer has interviews. We open an election form that weekend. 
- we are doing poll after this so vote lol 
- guru cards on responses of roles 
- beg of week 3, announce the board of Davis, week 3-4 training. 
-
