### ISSUE TITLE
Katie OKRs

### ISSUE THREAD

**Issue by beccatran** [bitprj/people#99]
**Objectives: Increase engagement and culture within Bit Project**

**Collaborators and Tasks**

- [ ] Find a way or ideas that team can do to bond remotely. You can research what other companies are doing. We need to see new members interact more in team meetings and slack in general. 
    - [ ] Different bonding socials: 1st meeting social, team social (biweekly), dept socials (once a month), organization social (once a month).  
- [ ] Create a social calendar (or update on the Bit Project Google Calendar)  schedule all socials within organization 

**Deadline: May 30th**

**Comment by beccatran** [comment]
Katie will help with develop socials and bonding activities :)

**Comment by kphillips20** [comment]
super excited, I can def do this!

**Comment by beccatran** [comment]
Update Katie?
@kphillips20

**Comment by kphillips20** [comment]
it's on my list of things to do :( 
definite plan can be complete by next weekend and first social could potentially be held then too
